In [1]:
import numpy as np
import pickle

In [2]:
with open('../../other_repos/ice-soil-planner/scripts/plan_saving/rewards_ice_soil.pickle', 'rb') as fh:
    data = pickle.load(fh)
    
print(len(data['eval'][0]))

10


In [3]:
rewards = [ d['rewards'] for d in data['eval'][6]]

print(len(rewards[2]))

print([np.min(d) for d in rewards])
print('\n')
print([np.max(d) for d in rewards])
print('\n')
#print([np.mean(d, axis=(0)) for d in rewards])
print(np.mean(np.array([np.mean(d, axis=(0)) for d in rewards]), axis=0))

print('\n\n\n0:')

rewards = [ d['rewards'] for d in data['eval'][2]]

print(len(rewards[2]))

print([np.min(d) for d in rewards])
print('\n')
print([np.max(d) for d in rewards])
print('\n')
#print([np.mean(d, axis=(0,1)) for d in rewards])
print(np.mean(np.array([np.mean(d, axis=(0)) for d in rewards]), axis=0))

print('\n\n\n\n\nMean of each reward vector')

for i, data_env in enumerate(data['eval']):
    rewards = [ d['rewards'] for d in data_env]
    print(str(i)+': '+ str(np.mean(np.array([np.mean(d, axis=(0)) for d in rewards]), axis=0)))

print('\n\n\n\n\n')
    
print(rewards)

444
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


[2.0696493306184296, 1.980367459656966, 1.9134934816023605, 2.0, 2.0620938410783323, 1.9613892420745782, 1.9459805395856606, 1.9602286654813785, 1.9816427108970776, 1.930977537309261]


[1.26378014 0.80948571 0.68478255 0.95787342 0.33950856]



0:
241
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


[1.8394687360988666, 1.9311064158259854, 1.862932892217469, 2.0348669967313047, 2.0, 1.9782053940413176, 1.7827869577034934, 1.9585865144470305, 2.0, 1.9997038840365373]


[1.18232157 0.81393605 0.58543088 0.95184578 0.3836945 ]





Mean of each reward vector
0: [0.76240644 0.81085502 0.90592372 0.95310414 0.32220371]
1: [0.2589115  0.78740758 1.08702374 0.95285534 0.36968486]
2: [1.18232157 0.81393605 0.58543088 0.95184578 0.3836945 ]
3: [0.86789165 0.81308705 0.82955845 0.95350066 0.37978235]
4: [0.88980673 0.82271688 0.65159411 0.94167387 0.3916099 ]
5: [0.8956727  0.79559201 0.85363528 0.94570512 0.30227742]
6: [1.26378014 0

In [4]:
all_rewards = [[ d['rewards'] for d in data_ev] for data_ev in data['eval']]

print([[np.min(r) for r in rew] for rew in all_rewards])
print('\n\n\n')
print([[np.max(r) for r in rew] for rew in all_rewards])

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]




[[1.3333333333333333, 2.1333333333333333, 1.4666666666666666, 1.4666666666666666, 1.6, 1.4666666666666666, 1.4666666666666666, 1.3333333333333333, 1.4666666666666666, 2.0], [1.4666666666666666, 1.3333333333333333, 1.3333333333333333, 1.2599999999999998, 1.4666666666666666, 1.4666666666666666, 1.4666666666666666, 1.6, 1.4666666666666666, 1.4666666666666666], [1.8394687360988666, 1.9311064158259854, 1.862932892217469, 2.0348669967313047, 2.0, 1.9782053940413176, 1.78278695

In [5]:
# with open('../../other_repos/ice-soil-planner/scripts/plan_saving/old_rewards_ice_soil.pickle', 'rb') as fh:
#     data_full = pickle.load(fh)
    
# print(np.min(data_full['train'][1][0]['rewards']))
# print(np.min(data['train'][0][1]['rewards']))

# data_full['eval'][1] = data['eval'][0]
# data_full['train'][1] = data['train'][0]

# print(np.min(data_full['train'][1][0]['rewards']))
# print(np.min(data['train'][0][1]['rewards']))

# with open('../../other_repos/ice-soil-planner/scripts/plan_saving/new_rewards_ice_soil.pickle', 'wb') as fh:
#     pickle.dump(data_full, fh)

In [9]:
data['train'][0][14]['rewards']

array([[1.02612468, 0.9       , 0.83134993, 0.96626863, 0.13333333],
       [0.63178794, 0.96      , 0.90471422, 0.96258263, 0.26666667],
       [1.15720622, 0.66      , 0.83906761, 0.92869137, 0.        ],
       ...,
       [0.79163679, 0.36      , 0.93782961, 0.95319027, 0.26666667],
       [0.73987674, 0.9       , 0.87080469, 0.9742119 , 0.26666667],
       [0.92341033, 0.9       , 0.88362347, 0.95741251, 0.26666667]])

In [7]:
from sklearn_extra.cluster import KMedoids

In [19]:
X = data['train'][0][4]['rewards']
kmed = KMedoids(n_clusters=60).fit(X)

cent = kmed.cluster_centers_

print(cent)

[[0.6714509  0.84       0.94413708 0.94629822 0.53333333]
 [0.8395871  0.78       0.95107456 0.96719454 0.26666667]
 [0.74529066 0.96       0.95409344 0.93221672 0.26666667]
 [0.81932458 1.02       0.86755343 0.95233496 0.26666667]
 [0.77756428 0.84       0.87811769 0.96303669 0.26666667]
 [0.84630256 0.84       0.92084061 0.95713673 0.26666667]
 [0.89847033 0.66       0.88408891 0.9404009  0.53333333]
 [0.81791245 0.84       0.88310402 0.95908304 0.26666667]
 [0.7740155  0.84       0.91042952 0.95827538 0.26666667]
 [0.70616871 0.84       0.94563602 0.96126089 0.26666667]
 [0.70426402 0.84       0.89780866 0.97681756 0.26666667]
 [0.81119605 0.84       0.90651243 0.95632777 0.26666667]
 [0.78480476 0.84       0.91313485 0.94901547 0.4       ]
 [0.71872781 0.9        0.93622015 0.94807538 0.26666667]
 [0.73805165 0.84       0.89556224 0.96063432 0.4       ]
 [0.77687344 0.84       0.92339865 0.93492057 0.26666667]
 [0.86015944 0.84       0.92041342 0.94839022 0.26666667]
 [0.78742546 0